# Note: Terraform cloud-init automatically deploys both frontend and backend
# Frontend: Built and served via nginx on port 80
# Backend: Runs as systemd service on port 3000
#
# App directory on VMs: training repo uses APP=/opt/bharatmart/BharatMart-App;
# flat repos (package.json at clone root) use APP=/opt/bharatmart.
# ============================================================================
# Git operations use clone root; npm/build use app dir (see README: app_source_subpath).
CLONE_ROOT="${CLONE_ROOT:-/opt/bharatmart}"
APP="${APP:-/opt/bharatmart/BharatMart-App}"

# STEP 1: Get IPs from Terraform outputs (run in your local terminal)
# ============================================================================
# Get Load Balancer Public IP (this is the frontend IP users will access)

# Get Frontend VM Public IPs (for SSH connection)

# Get Backend Instance Pool ID

# Save these values:
# LB_PUBLIC_IP=<load_balancer_public_ip>
# FRONTEND_VM_IP=<first_frontend_public_ip>
# BACKEND_POOL_ID=<backend_instance_pool_id>

# STEP 2: Verify Deployment Status
# ============================================================================
# Check if services are accessible via Load Balancer
curl http://LB_PUBLIC_IP
curl http://LB_PUBLIC_IP:3000/api/health

# STEP 3: Access Frontend VM, then Backend (if needed)
# ============================================================================
# On your laptop: copy the same private key Terraform uses onto the frontend, then SSH.
# Backend VMs are private — from the frontend, SSH to the backend private IP (see troubleshooting.md Outputs).
export KEY=~/.ssh/bharatmart_terraform_ed25519
export FE=<FRONTEND_VM_IP>
scp -i "$KEY" "$KEY" "opc@${FE}:~/.ssh/"
ssh -i "$KEY" "opc@${FE}" 'chmod 400 ~/.ssh/bharatmart_terraform_ed25519'
ssh -i "$KEY" "opc@${FE}"

# On the frontend, to reach a backend:
# ssh -i ~/.ssh/bharatmart_terraform_ed25519 opc@<BACKEND_PRIVATE_IP>

# Once on a VM, useful checks:

# Check nginx status
sudo systemctl status nginx

# Check if frontend files are deployed
ls -la /usr/share/nginx/html/

# View nginx logs
sudo tail -f /var/log/nginx/access.log
sudo tail -f /var/log/nginx/error.log

# Check cloud-init logs (to see if deployment completed)
sudo cat /var/log/cloud-init-output.log

# Restart nginx if needed
sudo systemctl restart nginx

# STEP 4: Backend VM (from Frontend)
# ============================================================================
# Get backend private IP from OCI Console using backend_instance_ids (troubleshooting.md Outputs), then:
# ssh -i ~/.ssh/bharatmart_terraform_ed25519 opc@<BACKEND_PRIVATE_IP>

# On the backend:

# Check backend service status
sudo systemctl status bharatmart-backend

# View backend service logs
sudo journalctl -u bharatmart-backend -f

# Check if backend is running
ps aux | grep node

# Check backend port
sudo netstat -tlnp | grep 3000

# Restart backend service if needed
sudo systemctl restart bharatmart-backend

# View cloud-init logs
sudo cat /var/log/cloud-init-output.log

# Check .env file (auto-generated by Terraform)
cat "$APP/.env"

# STEP 5: Manual Deployment (if cloud-init failed or needs update)
# ============================================================================
# If you need to manually deploy or update, follow these steps:

# On Frontend VM:
cd "$CLONE_ROOT"
git pull
cd "$APP"
npm install
npm run build
sudo rm -rf /usr/share/nginx/html/*
sudo cp -r dist/* /usr/share/nginx/html/
sudo systemctl restart nginx

# On Backend VM (access via Frontend VM):
cd "$CLONE_ROOT"
git pull
cd "$APP"
npm install
npm run build:server
sudo systemctl restart bharatmart-backend

# STEP 6: View Application Logs
# ============================================================================
# Backend logs (on Backend VM):
sudo journalctl -u bharatmart-backend -n 100
sudo journalctl -u bharatmart-backend -f

# Frontend nginx logs (on Frontend VM):
sudo tail -f /var/log/nginx/access.log
sudo tail -f /var/log/nginx/error.log

# Application logs (if configured):
tail -f "$APP/logs/api.log"

# STEP 7: Check Load Balancer Health
# ============================================================================
# From your local terminal, check backend health:
curl http://LB_PUBLIC_IP:3000/api/health

# Check frontend:
curl http://LB_PUBLIC_IP

# ============================================================================
# Access URLs (use Load Balancer Public IP from step 1):
# ============================================================================
# Frontend: http://LB_PUBLIC_IP
# Backend API: http://LB_PUBLIC_IP:3000/api
# Backend Health Check: http://LB_PUBLIC_IP:3000/api/health
